# Generated by Django 4.0.4 on 2022-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=200, verbose_name='Article title')),
                ('synopsis', models.CharField(default='null', max_length=312, null=True, verbose_name='Article synopsis')),
                ('img', models.ImageField(upload_to='')),
                ('url', models.CharField(default='#', max_length=200, null=True, verbose_name='Article URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Article Created')),
            ],
        ),
    ]
